export const MOVIES_REQUEST = 'MOVIES_REQUEST';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const TOGGLE_BASKET = 'TOGGLE_BASKET';
export const NOMINATE_MOVIE = 'NOMINATE_MOVIE';
export const UNDO_NOMINATE_MOVIE = 'UNDO_NOMINATE_MOVIE';
